<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTOoZftL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTOoZftL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTOoZftL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTOoZftL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTOoZftL\App_KernelDevDebugContainer([
    'container.build_hash' => 'TOoZftL',
    'container.build_id' => '6caf58aa',
    'container.build_time' => 1783412259,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTOoZftL');
