<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => ['/build/runtime.d5f83a3a.js', '/build/72.3e1abc75.js', '/build/app.dea52ec2.js'],
            'css' => ['/build/72.801cc83f.css', '/build/app.6d71f15a.css'],
        ],
    ],
],

]];
